#!/usr/bin/env python3
"""
Data Visualization Script for DDS-ROS2 Bridge Logged Data

This script reads the CSV files generated by the dds_ros2_bridge_node
and creates visualizations of the logged robot data.

Usage:
    python3 visualize_logged_data.py <csv_file>
    
Example:
    python3 visualize_logged_data.py logged_data_20250129_143000.csv
"""

import sys
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import argparse
from pathlib import Path

def parse_arguments():
    parser = argparse.ArgumentParser(description='Visualize DDS-ROS2 Bridge logged data')
    parser.add_argument(
        'csv_file',
        nargs='?',  # 使 csv_file 参数变为可选
        default='~/jazzy_ws/data/logged_data_20250911_013143.csv',  # 设置默认值
        help='Path to the CSV file to visualize (default: logged_data.csv)'
    )
    parser.add_argument('--save', action='store_true', default=True, help='Save plots as PNG files')
    parser.add_argument('--show', action='store_true', default=False, help='Show plots on screen (default: True)')
    parser.add_argument('--motor-id', type=int, default=0, help='Motor ID to plot detailed data for (0-19)')
    return parser.parse_args()

def load_data(csv_file):
    """Load and parse the CSV data"""
    try:
        df = pd.read_csv(csv_file)
        print(f"Loaded {len(df)} data points from {csv_file}")
        return df
    except Exception as e:
        print(f"Error loading CSV file: {e}")
        return None

def plot_imu_data(df, save_plots=False, save_dir=None):
    """Plot IMU data (quaternions, gyroscope, accelerometer, RPY)"""
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))
    
    # Quaternion
    axes[0, 0].plot(df['timestamp'], df['imu_quat_w'], label='w')
    axes[0, 0].plot(df['timestamp'], df['imu_quat_x'], label='x')
    axes[0, 0].plot(df['timestamp'], df['imu_quat_y'], label='y')
    axes[0, 0].plot(df['timestamp'], df['imu_quat_z'], label='z')
    axes[0, 0].set_title('IMU Quaternion')
    axes[0, 0].set_xlabel('Time (s)')
    axes[0, 0].set_ylabel('Quaternion Components')
    axes[0, 0].legend()
    axes[0, 0].grid(True)
    
    # Gyroscope
    axes[0, 1].plot(df['timestamp'], df['imu_gyro_x'], label='x')
    axes[0, 1].plot(df['timestamp'], df['imu_gyro_y'], label='y')
    axes[0, 1].plot(df['timestamp'], df['imu_gyro_z'], label='z')
    axes[0, 1].set_title('IMU Gyroscope')
    axes[0, 1].set_xlabel('Time (s)')
    axes[0, 1].set_ylabel('Angular Velocity (rad/s)')
    axes[0, 1].legend()
    axes[0, 1].grid(True)
    
    # Accelerometer
    axes[1, 0].plot(df['timestamp'], df['imu_accel_x'], label='x')
    axes[1, 0].plot(df['timestamp'], df['imu_accel_y'], label='y')
    axes[1, 0].plot(df['timestamp'], df['imu_accel_z'], label='z')
    axes[1, 0].set_title('IMU Accelerometer')
    axes[1, 0].set_xlabel('Time (s)')
    axes[1, 0].set_ylabel('Acceleration (m/s²)')
    axes[1, 0].legend()
    axes[1, 0].grid(True)
    
    # Roll-Pitch-Yaw
    axes[1, 1].plot(df['timestamp'], np.degrees(df['imu_rpy_r']), label='Roll')
    axes[1, 1].plot(df['timestamp'], np.degrees(df['imu_rpy_p']), label='Pitch')
    axes[1, 1].plot(df['timestamp'], np.degrees(df['imu_rpy_y']), label='Yaw')
    axes[1, 1].set_title('IMU Roll-Pitch-Yaw')
    axes[1, 1].set_xlabel('Time (s)')
    axes[1, 1].set_ylabel('Angle (degrees)')
    axes[1, 1].legend()
    axes[1, 1].grid(True)
    
    plt.tight_layout()
    
    if save_plots:
        if save_dir is not None:
            save_path = Path(save_dir) / 'imu_data.png'
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"Saved IMU plot as {save_path}")
        else:
            plt.savefig('imu_data.png', dpi=300, bbox_inches='tight')
            print("Saved IMU plot as imu_data.png")
    
    return fig

def plot_motor_data(df, motor_id=0, save_plots=False, save_dir=None, show_only=False):
    """Plot detailed motor data for a specific motor"""
    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    
    # Motor position (q)
    axes[0, 0].plot(df['timestamp'], df[f'motor_{motor_id}_q'], label='Actual', color='blue')
    axes[0, 0].plot(df['timestamp'], df[f'cmd_motor_{motor_id}_q'], label='Command', color='red', linestyle='--')
    axes[0, 0].set_title(f'Motor {motor_id} Position')
    axes[0, 0].set_xlabel('Time (s)')
    axes[0, 0].set_ylabel('Position (rad)')
    axes[0, 0].legend()
    axes[0, 0].grid(True)
    
    # Motor velocity (dq)
    axes[0, 1].plot(df['timestamp'], df[f'motor_{motor_id}_dq'], label='Actual', color='blue')
    axes[0, 1].plot(df['timestamp'], df[f'cmd_motor_{motor_id}_dq'], label='Command', color='red', linestyle='--')
    axes[0, 1].set_title(f'Motor {motor_id} Velocity')
    axes[0, 1].set_xlabel('Time (s)')
    axes[0, 1].set_ylabel('Velocity (rad/s)')
    axes[0, 1].legend()
    axes[0, 1].grid(True)
    
    # Motor torque
    axes[0, 2].plot(df['timestamp'], df[f'motor_{motor_id}_tau'], label='Estimated', color='blue')
    axes[0, 2].plot(df['timestamp'], df[f'cmd_motor_{motor_id}_tau'], label='Command', color='red', linestyle='--')
    axes[0, 2].set_title(f'Motor {motor_id} Torque')
    axes[0, 2].set_xlabel('Time (s)')
    axes[0, 2].set_ylabel('Torque (Nm)')
    axes[0, 2].legend()
    axes[0, 2].grid(True)
    
    # Motor acceleration (ddq)
    axes[1, 0].plot(df['timestamp'], df[f'motor_{motor_id}_ddq'], color='blue')
    axes[1, 0].set_title(f'Motor {motor_id} Acceleration')
    axes[1, 0].set_xlabel('Time (s)')
    axes[1, 0].set_ylabel('Acceleration (rad/s²)')
    axes[1, 0].grid(True)
    
    # Motor temperature
    axes[1, 1].plot(df['timestamp'], df[f'motor_{motor_id}_temperature'], color='orange')
    axes[1, 1].set_title(f'Motor {motor_id} Temperature')
    axes[1, 1].set_xlabel('Time (s)')
    axes[1, 1].set_ylabel('Temperature (°C)')
    axes[1, 1].grid(True)
    
    # Control gains
    axes[1, 2].plot(df['timestamp'], df[f'cmd_motor_{motor_id}_kp'], label='Kp', color='green')
    axes[1, 2].plot(df['timestamp'], df[f'cmd_motor_{motor_id}_kd'], label='Kd', color='purple')
    axes[1, 2].set_title(f'Motor {motor_id} Control Gains')
    axes[1, 2].set_xlabel('Time (s)')
    axes[1, 2].set_ylabel('Gain Value')
    axes[1, 2].legend()
    axes[1, 2].grid(True)
    
    plt.tight_layout()
    if save_plots:
        if save_dir is not None:
            save_path = Path(save_dir) / f'motor_{motor_id}_data.png'
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"Saved motor {motor_id} plot as {save_path}")
        else:
            plt.savefig(f'motor_{motor_id}_data.png', dpi=300, bbox_inches='tight')
            print(f"Saved motor {motor_id} plot as motor_{motor_id}_data.png")
    if show_only:
        plt.show()
    plt.close(fig)
    return fig

def plot_motor_overview(df, save_plots=False, save_dir=None):
    """Plot overview of all motor positions, velocities, and torques"""
    fig, axes = plt.subplots(3, 1, figsize=(15, 15))
    
    # All motor positions
    for i in range(12):
        axes[0].plot(df['timestamp'], df[f'motor_{i}_q'], label=f'Motor {i}', alpha=0.7)
    axes[0].set_title('All Motor Positions')
    axes[0].set_xlabel('Time (s)')
    axes[0].set_ylabel('Position (rad)')
    axes[0].grid(True)
    handles, labels = axes[0].get_legend_handles_labels()
    # axes[0].legend(handles[:4], labels[:4], title='Sample Motors')
    axes[0].legend(handles[:], labels[:], title='All Motors', loc='upper right')
    
    # All motor velocities
    for i in range(12):
        axes[1].plot(df['timestamp'], df[f'motor_{i}_dq'], label=f'Motor {i}', alpha=0.7)
    axes[1].set_title('All Motor Velocities')
    axes[1].set_xlabel('Time (s)')
    axes[1].set_ylabel('Velocity (rad/s)')
    axes[1].grid(True)
    handles, labels = axes[1].get_legend_handles_labels()
    # axes[1].legend(handles[:4], labels[:4], title='Sample Motors')
    axes[1].legend(handles[:], labels[:], title='All Motors', loc='upper right')
    
    # All motor torques
    for i in range(12):
        axes[2].plot(df['timestamp'], df[f'motor_{i}_tau'], label=f'Motor {i}', alpha=0.7)
    axes[2].set_title('All Motor Torques')
    axes[2].set_xlabel('Time (s)')
    axes[2].set_ylabel('Torque (Nm)')
    axes[2].grid(True)
    handles, labels = axes[2].get_legend_handles_labels()
    # axes[2].legend(handles[:4], labels[:4], title='Sample Motors')
    axes[2].legend(handles[:], labels[:], title='All Motors', loc='upper right')
    
    plt.tight_layout()
    
    if save_plots:
        if save_dir is not None:
            save_path = Path(save_dir) / 'motor_overview.png'
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"Saved motor overview plot as {save_path}")
        else:
            plt.savefig('motor_overview.png', dpi=300, bbox_inches='tight')
            print("Saved motor overview plot as motor_overview.png")
    
    return fig

def print_data_summary(df):
    """Print summary statistics of the logged data"""
    print("\n" + "="*50)
    print("DATA SUMMARY")
    print("="*50)
    print(f"Duration: {df['timestamp'].iloc[-1]:.2f} seconds")
    print(f"Sample rate: {len(df) / df['timestamp'].iloc[-1]:.1f} Hz")
    print(f"Data points: {len(df)}")
    
    print("\nIMU Summary:")
    print(f"  Temperature range: {df['imu_temperature'].min():.1f} - {df['imu_temperature'].max():.1f} °C")
    print(f"  Max acceleration magnitude: {np.sqrt(df['imu_accel_x']**2 + df['imu_accel_y']**2 + df['imu_accel_z']**2).max():.2f} m/s²")
    print(f"  Max angular velocity magnitude: {np.sqrt(df['imu_gyro_x']**2 + df['imu_gyro_y']**2 + df['imu_gyro_z']**2).max():.2f} rad/s")
    
    print("\nMotor Summary:")
    motor_temps = [df[f'motor_{i}_temperature'] for i in range(20)]
    all_temps = pd.concat(motor_temps)
    print(f"  Motor temperature range: {all_temps.min():.1f} - {all_temps.max():.1f} °C")
    
    motor_torques = [df[f'motor_{i}_tau'] for i in range(20)]
    all_torques = pd.concat(motor_torques)
    print(f"  Motor torque range: {all_torques.min():.2f} - {all_torques.max():.2f} Nm")

def main():
    args = parse_arguments()
    
    # Check if file exists
    csv_file = Path(args.csv_file).expanduser()
    if not csv_file.exists():
        print(f"Error: File {csv_file} does not exist")
        sys.exit(1)
    
    # Load data
    df = load_data(csv_file)
    if df is None:
        sys.exit(1)
    
    # Print summary
    print_data_summary(df)
    
    # Create visualizations
    print("\nGenerating plots...")
    save_dir = None
    if args.save:
        save_dir = csv_file.parent / csv_file.stem
        save_dir.mkdir(parents=True, exist_ok=True)
    fig1 = plot_imu_data(df, args.save, save_dir)
    fig2 = plot_motor_overview(df, args.save, save_dir)
    if args.save:
        # 保存所有电机的图片
        for mid in range(12):
            plot_motor_data(df, mid, save_plots=True, save_dir=save_dir, show_only=False)
        print("Saved all motor detailed plots.")
    if args.show:
        # 只显示指定电机的图片
        plot_motor_data(df, args.motor_id, save_plots=False, save_dir=None, show_only=True)
    print(f"\nGenerated plots:")
    print("1. IMU data (quaternion, gyroscope, accelerometer, RPY)")
    print("2. Motor overview (all motor positions, velocities, torques)")
    print("3. Detailed motor plots (see saved files or show window)")
    print("\nVisualization complete!")

if __name__ == "__main__":
    main()
